### PR TITLE
feat: nicer error stack

### PR DESCRIPTION
**Pull request by P0lip**
As discussed on Slack.

### CODE REVIEW

**Comment by P0lip** [comment]
Hmmm 
image
https://app.circleci.com/pipelines/github/stoplightio/react-error-boundary/12/workflows/8be506be-6376-4bd3-bb26-1e2d7b7fc2cb/jobs/22

**Comment by marbemac** [comment]
Did you mention somewhere that this doesn't really work because of the minification? If so, any ideas that aren't too complicated?

Does the original error not have the stack in it already (like a regular error call stack) that might work if source maps worked ok in sentry or something? E.g. if an error occurred is thrown in the render method of a component, and it was not handled by react-error-boundary, would we have decent visibility/debuggability in sentry? If so, why are we losing that when things are caught and re-thrown by error boundary?

**Comment by marbemac** [comment]
Fixed the CI issue btw - circle needed the deploy key regenerated for some reason 🤷‍♂️

**Comment by P0lip** [comment]
> Did you mention somewhere that this doesn't really work because of the minification? If so, any ideas that aren't too complicated?

Correct, out of curiosity I had a try and here's an example stack I managed to collect

```
    in c
    in div
    in div
    in div
    in div
    in div
    in n
    in ScrollContainer
    in ForwardRef
    in t
    in div
    in t
    in Unknown
    in FixedSizeList
    in div
    in Y
    in c
    in z
    in u
    in TreeList
    in c
    in c
    in div
    in t
    in div
    in c
    in div
    in Box
    in ForwardRef
    in ForwardRef
    in c
    in div
    in t
    in div
    in c
    in c
    in div
    in u
    in s
    in c
    in Unknown
    in Suspense
    in t
    in Unknown
    in Unknown
    in Unknown
    in RequiresWorkspace(Component)
    in RequiresAuth(RequiresWorkspace(Component))
    in RequiresAuth(RequiresWorkspace(Component))
    in div
    in t
    in H
    in t
    in M
    in B
    in Unknown
    in Unknown
    in u
    in WithErrorBoundary(PureRouteMemo(Component))
    in div
    in t
    in H
    in t
    in M
    in B
    in div
    in Cs
    in js
    in As
    in div
    in Zu
    in zr
    in Ju
    in Unknown
    in c
    in WithQueryClientProvider(Component)
    in xe
    in F
    in s
    in Unknown
    in c
    in HelmetProvider
    in t
    in div
    in Cs
    in js
    in As
    in div
    in Zu
    in zr
    in Ju
    in div
    in Box
    in pi
```

Ideas, listed from the least work required:

- `terser` and its `keep_fnames` which is false by default. We could flip it on and see the size of the bundle increased.
Since we use PascalCase for components, we could try to supply a regular expression that would match that particular case. By doing so, we'd strip most of the names besides the ones for classes/constructors, and obviously components that are desired here.

- `displayName` - as you can see  in the stack above, components that have `displayName` are rendered nicely

> Does the original error not have the stack in it already (like a regular error call stack) that might work if source maps worked ok in sentry or something?
 E.g. if an error occurred is thrown in the render method of a component, and it was not handled by react-error-boundary, would we have decent visibility/debuggability in sentry? If so, why are we losing that when things are caught and re-thrown by error boundary?


It does, but it's a React stack, which is rather useless, in particular in the world of hooks.
Example stack:
```
  Error: Uncaught [TypeError: String expected]
        at reportException (/Users/jakub/Developer/react-error-boundary/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
        at invokeEventListeners (/Users/jakub/Developer/react-error-boundary/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:209:9)
        at HTMLUnknownElementImpl._dispatch (/Users/jakub/Developer/react-error-boundary/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
        at HTMLUnknownElementImpl.dispatchEvent (/Users/jakub/Developer/react-error-boundary/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
        at HTMLUnknownElementImpl.dispatchEvent (/Users/jakub/Developer/react-error-boundary/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
        at HTMLUnknownElement.dispatchEvent (/Users/jakub/Developer/react-error-boundary/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
        at Object.invokeGuardedCallbackDev (/Users/jakub/Developer/react-error-boundary/node_modules/react-dom/cjs/react-dom.development.js:397:16)
        at invokeGuardedCallback (/Users/jakub/Developer/react-error-boundary/node_modules/react-dom/cjs/react-dom.development.js:454:31)
        at beginWork$$1 (/Users/jakub/Developer/react-error-boundary/node_modules/react-dom/cjs/react-dom.development.js:23217:7)
        at performUnitOfWork (/Users/jakub/Developer/react-error-boundary/node_modules/react-dom/cjs/react-dom.development.js:22211:12) TypeError: String expected
        at Suite.Object.<anonymous>.describe (/Users/jakub/Developer/react-error-boundary/src/__tests__/ErrorBoundary.test.tsx:11:14)
        at addSpecsToSuite (/Users/jakub/Developer/react-error-boundary/node_modules/jest-jasmine2/build/jasmine/Env.js:496:51)
```
vs what React gives us (the `componentStack` prop)
```
  The above error occurred in the <TestComponent> component:
        in TestComponent (created by TestComponent2)
        in TestComponent2 (created by TestComponent3)
        in TestComponent3 (created by TestComponent4)
        in TestComponent4
        in ErrorBoundary
        in Unknown (created by WrapperComponent)
        in WrapperComponent
```
so answering your other question - it's rather far from decent.
It's same as you'd try to debug React app in the debugger - almost impossible, as the call stack is totally not related to the actual components, unless you use class components and have some method that fails there, but this is irrelevant in our scenario as we're all about function components.

I also had a quick check 
image

and the stack here seems to be almost all pointing at some React code instead of ours.

**Comment by P0lip** [comment]
Screw it.

**Pull request closed without merging**
